name: Auto update changelog

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  auto-update-changlog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up git-cliff
        uses: kenji-miyake/setup-git-cliff@v1

      - name: Update changelog
        run: |
          git cliff -o CHANGELOG.md

      - name: Push to GitHub
        continue-on-error: true
        run: |
            git config user.name "Heathcliff"
            git pull
            git add . || exit 0
            git commit -snm "chore: auto update changelog at $(date '+%F %H:%M.%S')" || exit 0
            git push || exit 0