name: Build dists and docs

on:
  push:
  pull_request:

permissions: 
  contents: write

jobs:
  dist-and-docs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.8', '3.x' ]

    name: Build dist and install (${{ matrix.python-version }})
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up CPython ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Build distributions
        run: |
          python ./setup.py sdist bdist_wheel

      - name: Install package
        run: |
          pip install -e .[dev,docs]

      - name: Build docs
        shell: bash
        run: |
          cd docs
          sphinx-build -b html --keep-going . _build/
          cd ..

      - name: Upload docs
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: docs/_build